// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTboAdYRIWLdzuJmQVV68_p8pC_aRjueM',
    appId: '1:570436458803:web:fdd52b638cb38b794ac646',
    messagingSenderId: '570436458803',
    projectId: 'municipios-6095a',
    authDomain: 'municipios-6095a.firebaseapp.com',
    storageBucket: 'municipios-6095a.firebasestorage.app',
    measurementId: 'G-EF0V2ES0TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJHj7EIU-0-APRk16ju6-oP3z3bolav5Y',
    appId: '1:570436458803:android:daf10fa99be477714ac646',
    messagingSenderId: '570436458803',
    projectId: 'municipios-6095a',
    storageBucket: 'municipios-6095a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_145EMS8Z08hCh_e4xk1Wz7hwbW-qfc',
    appId: '1:570436458803:ios:c7c6fa31cc30d8cc4ac646',
    messagingSenderId: '570436458803',
    projectId: 'municipios-6095a',
    storageBucket: 'municipios-6095a.firebasestorage.app',
    iosBundleId: 'com.example.municipiosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_145EMS8Z08hCh_e4xk1Wz7hwbW-qfc',
    appId: '1:570436458803:ios:c7c6fa31cc30d8cc4ac646',
    messagingSenderId: '570436458803',
    projectId: 'municipios-6095a',
    storageBucket: 'municipios-6095a.firebasestorage.app',
    iosBundleId: 'com.example.municipiosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTboAdYRIWLdzuJmQVV68_p8pC_aRjueM',
    appId: '1:570436458803:web:3b49d779952e9aa94ac646',
    messagingSenderId: '570436458803',
    projectId: 'municipios-6095a',
    authDomain: 'municipios-6095a.firebaseapp.com',
    storageBucket: 'municipios-6095a.firebasestorage.app',
    measurementId: 'G-K4GCSH8Y4D',
  );
}
